### ISSUE TITLE
Java version error

### ISSUE THREAD

**Issue by Bleach665** [dernasherbrezon/rtlSpectrum#4]
Windows 10, Java ver 1.8.0_251.
I try to execute rtlSpectrum
`java -jar rtlSpectrum.jar`
and receive an error:
````
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: ru/r2cloud/rtlspectrum/Main has been compiled by a more recent version of the Java Runtime
 (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
````
The latest Java version is already installed:
![javaw_jO4ATXrnMV](https://user-images.githubusercontent.com/6595124/79747554-8c05db00-8314-11ea-9720-c29ccb804fca.png)

**Comment by dernasherbrezon** [comment]
Yes, java 8 is no longer supported. You have:

> Java ver 1.8.0_251.

This screenshot says you have the latest java 8. Not the latest java.

**Comment by Bleach665** [comment]
This is sad because as far as I understood, for Windows last java version is 8.

**Comment by dernasherbrezon** [comment]
You can download 8, 11 (LTS) and 14. They can be installed in parallel:
https://www.oracle.com/java/technologies/javase-downloads.html
